name: GitHub Actions Redait
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GATSBY_STRAPI_URL: https://strapi.redait.cloudspaceclient.com
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Show access key ID
        run: aws sts get-caller-identity --output=yaml
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-redait-web-app-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-redait-web-app-build-
      - name: Install dependencies
        run: yarn install
      # - name: Run Lint
      #   run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Deploy to S3
        # run: yarn run deploy
        run: yarn run deploy
